In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import math
!pip install arch


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 7.8 MB/s eta 0:00:00


In [ ]:
#!pip install networkx==2.5.1
#import networkx as nx

In [ ]:
from arch import arch_model

In [ ]:
#import statsmodels
from statsmodels.tsa.api import VAR

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
ticker_symbol=[47]
data2023=[]
ticker_symbol=['ADANIENT.NS','ADANIPORTS.NS','SHRIRAMFIN.NS','COALINDIA.NS','TATASTEEL.NS','BAJFINANCE.NS','BAJAJ-AUTO.NS','APOLLOHOSP.NS','LT.NS','INDUSINDBK.NS','M&M.NS','SBIN.NS','POWERGRID.NS','ITC.NS','HDFCBANK.NS','ICICIBANK.NS','INFY.NS','WIPRO.NS','BPCL.NS','BAJAJFINSV.NS','RELIANCE.NS','SUNPHARMA.NS','KOTAKBANK.NS','ULTRACEMCO.NS','TATAMOTORS.NS','NTPC.NS','EICHERMOT.NS','ASIANPAINT.NS','BRITANNIA.NS','HEROMOTOCO.NS','JSWSTEEL.NS','AXISBANK.NS','ONGC.NS','BHARTIARTL.NS','HCLTECH.NS','TITAN.NS','TECHM.NS','GRASIM.NS','HINDUNILVR.NS','TCS.NS','TATACONSUM.NS','CIPLA.NS','HINDALCO.NS','MARUTI.NS','DRREDDY.NS','NESTLEIND.NS','DIVISLAB.NS']
start_date='2020-08-01'
close_date='2023-08-01'

for i in range(47):
  data2023.append(yf.download(ticker_symbol[i],start=start_date,end=close_date))


[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

In [ ]:
for i in range(len(ticker_symbol)):
  for j in range(len(data2023[i])):
    data2023[i]=data2023[i].assign(returns=((np.log(data2023[i]['Close']))-(np.log(data2023[i]['Close'].shift(1)))))

In [ ]:
for i in range(len(ticker_symbol)):
  data2023[i]['returns'][0]=0
  model=arch_model(data2023[i]['returns'],p=1,q=1)
  model_fit=model.fit(disp='off')
  data2023[i]=data2023[i].assign(conditional_volatality=(np.power(model_fit.conditional_volatility,3/2)))

In [ ]:
input=[np.array(data2023[i]['returns']) for i in range(len(ticker_symbol))]
print(len(input))
corr_matrix = np.corrcoef(input)
print(corr_matrix)

47
[[1.         0.69379011 0.22728834 ... 0.09374158 0.0793203  0.17749417]
 [0.69379011 1.         0.30311489 ... 0.14630024 0.12484065 0.1680883 ]
 [0.22728834 0.30311489 1.         ... 0.07957494 0.06358405 0.1387325 ]
 ...
 [0.09374158 0.14630024 0.07957494 ... 1.         0.23812642 0.39117005]
 [0.0793203  0.12484065 0.06358405 ... 0.23812642 1.         0.21987697]
 [0.17749417 0.1680883  0.1387325  ... 0.39117005 0.21987697 1.        ]]


In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
#print(eigenvalues)
#Find the principal eigenvector
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]
print('largest index:',largest_index,'\nprincipal eigenvector:',principal_eigenvector)

largest index: 0 
principal eigenvector: [0.12507384 0.15815284 0.1418207  0.13664034 0.16445067 0.18118814
 0.13405531 0.10446474 0.17799457 0.16629568 0.16944103 0.18494261
 0.11079133 0.13734873 0.15769995 0.17784824 0.13668592 0.14636174
 0.13837907 0.17680051 0.14345455 0.13745356 0.15259348 0.1636912
 0.17845887 0.13632705 0.1538471  0.11992682 0.09562019 0.15010942
 0.16276322 0.16781991 0.10048648 0.13660909 0.13162983 0.15810407
 0.14388781 0.18260519 0.10704801 0.13508561 0.15803514 0.07649912
 0.16462037 0.14985841 0.09245993 0.10236977 0.11306302]


In [ ]:
def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices2023 = get_sorted_indices(eve.copy())

for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices2023[i]])

ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
POWERGRID.NS
ITC.NS
ICICIBANK.NS
WIPRO.NS
BPCL.NS
BAJAJFINSV.NS
RELIANCE.NS
SUNPHARMA.NS
KOTAKBANK.NS
HEROMOTOCO.NS
JSWSTEEL.NS
AXISBANK.NS
ONGC.NS
TECHM.NS
GRASIM.NS
HINDALCO.NS
MARUTI.NS
DRREDDY.NS
DIVISLAB.NS
NESTLEIND.NS
CIPLA.NS
TATACONSUM.NS
TCS.NS
HINDUNILVR.NS
TITAN.NS
HCLTECH.NS
BHARTIARTL.NS
BRITANNIA.NS
ASIANPAINT.NS
EICHERMOT.NS
NTPC.NS
TATAMOTORS.NS
ULTRACEMCO.NS
INFY.NS
HDFCBANK.NS


In [ ]:
df = pd.concat([data2023[i]['returns'] for i in range(len(ticker_symbol))],axis=1)
returns=pd.DataFrame(df)
#print(returns)
model = VAR(returns)
var_result = model.fit(1)  # Fit model with lag 1

# Print summary of the results
print(var_result.summary())

# Get the covariance matrix of residuals
covariance_matrix = var_result.sigma_u

# Perform Cholesky decomposition
chol_matrix = np.linalg.cholesky(covariance_matrix)

# Print Cholesky matrix
print("Cholesky Matrix:\n", chol_matrix)

# Calculate orthogonalized impulse responses
# For demonstration, compute impulse responses for 10 periods


  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Fri, 07, Jun, 2024
Time:                     09:38:36
--------------------------------------------------------------------
No. of Equations:         47.0000    BIC:                   -385.090
Nobs:                     744.000    HQIC:                  -393.685
Log likelihood:           101095.    FPE:               4.86962e-174
AIC:                     -399.075    Det(Omega_mle):    2.57834e-175
--------------------------------------------------------------------
Results for equation returns
                coefficient       std. error           t-stat            prob
-----------------------------------------------------------------------------
const              0.003259         0.001386            2.351           0.019
L1.returns         0.106653         0.053298            2.001           0.045
L1.returns         0.105650         0.082696            1.278         

In [ ]:
irf = var_result.irf(10)
orth_irf = irf.orth_irfs
print("Orthogonalized Impulse Responses:\n", orth_irf)

Orthogonalized Impulse Responses:
 [[[ 3.69940596e-02  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 1.80679151e-02  1.85020105e-02  0.00000000e+00 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  [ 5.82562185e-03  5.43394507e-03  2.39805356e-02 ...  0.00000000e+00
    0.00000000e+00  0.00000000e+00]
  ...
  [ 1.51265627e-03  1.78075750e-03  1.31951903e-04 ...  1.22688555e-02
    0.00000000e+00  0.00000000e+00]
  [ 9.57447639e-04  1.26289772e-03  4.12290531e-04 ...  5.36736710e-04
    9.07189265e-03  0.00000000e+00]
  [ 3.04126151e-03  1.50046850e-03  1.55549986e-03 ...  2.56738920e-03
    7.54923179e-04  1.48679746e-02]]

 [[ 5.15278189e-03  9.45718957e-04 -1.64116611e-03 ... -1.61653420e-03
    1.29085056e-03 -5.90556007e-04]
  [ 9.82096082e-04  1.22232300e-03  9.25471561e-04 ... -1.18279282e-03
   -8.99681933e-04 -1.41879357e-03]
  [ 1.13459177e-03  2.13395135e-04 -3.41489818e-05 ...  5.51311109e-04
    1.48966229e-03 -6.64258405

In [ ]:
!pip install networkx matplotlib pygraphviz
!apt-get -qq install -y graphviz libgraphviz-dev pkg-config
import networkx as nx
import matplotlib matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import numpy as np

def create_mst_from_correlation(correlation_matrix):
  """
  Creates a minimum spanning tree (MST) from a correlation matrix.

  Args:
    correlation_matrix: A 2D numpy array representing the correlation matrix.

  Returns:
    A networkx minimum spanning tree object.
  """

  # Handle potential errors in correlation matrix
  if correlation_matrix is None or not isinstance(correlation_matrix, np.ndarray):
    raise ValueError("Invalid correlation matrix provided.")

  # Invert the correlation matrix to prioritize stronger negative correlations for edge weights
  edge_weights = 1 - np.abs(correlation_matrix)

  # Create a complete graph from the edge weights
  graph = nx.from_numpy_matrix(edge_weights, create_using=nx.complete_graph(correlation_matrix.shape[0]))

  # Calculate the minimum spanning tree of the graph
  mst = nx.minimum_spanning_tree(graph)

  return mst

# Example usage (replace with your actual correlation matrix)
# corr_matrix = np.array([[1, 0.5, 0.2], [0.5, 1, 0.7], [0.2, 0.7, 1]])
mst = create_mst_from_correlation(corr_matrix)

# Print information about the MST
print("Number of nodes in MST:", mst.number_of_nodes())
print("Number of edges in MST:", mst.number_of_edges())

# Print edges in the MST
for edge in mst.edges():
    print(edge)

# Visualize the MST
# If you are in a non-interactive environment, uncomment the following line:
plt.switch_backend('agg')
nx.draw(mst, with_labels=True)
plt.show()


IndentationError: unexpected indent (<ipython-input-24-be555744263d>, line 5)

In [ ]:
!pip install slicematrixIO
from slicematrixIO import SliceMatrix as sm

# Assuming 'returns' is your pandas DataFrame
mst = sm.MinimumSpanningTree(dataset =returns)
results = mst.fit()
print(results.summary())

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.6/468.6 kB 7.1 MB/s eta 0:00:00
  Created wheel for slicematrixIO: filename=slicematrixIO-0.1.8-py3-none-any.whl size=39701 sha256=00d31939124f123515a46d5b69007c71806c3d1b715ffee67f3adfc1662b6138
  Stored in directory: /root/.cache/pip/wheels/64/61/50/04f4bccd5103a40c212c371d4c6208ad26f0807c99820efa16
Successfully built slicematrixIO
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 1.8.0 requires requests>=2.27.1, but you have requests 2.5.3 which is incompatible.
cachecontrol 0.14.0 requires requests>=2.16.0, but you have requests 2.5.3 which is incompatible.
google-api-core 2.11.1 requires requests<3.

ModuleNotFoundError: No module named 'client'

In [ ]:
!pip show networkx
!pip.show matplotlib
!jupyter --version

Name: networkx
Version: 2.5.1
Summary: Python package for creating and manipulating graphs and networks
Home-page: http://networkx.github.io/
Author: Aric Hagberg
Author-email: hagberg@lanl.gov
License: UNKNOWN
Location: /usr/local/lib/python3.10/dist-packages
Requires: decorator
Required-by: hyperopt, python-louvain, scikit-image, torch
/bin/bash: line 1: pip.show: command not found
Selected Jupyter core packages...
IPython          : 7.34.0
ipykernel        : 5.5.6
ipywidgets       : 7.7.1
jupyter_client   : 6.1.12
jupyter_core     : 5.7.2
jupyter_server   : 1.24.0
jupyterlab       : not installed
nbclient         : 0.10.0
nbconvert        : 6.5.4
nbformat         : 5.10.4
notebook         : 6.5.5
qtconsole        : not installed
traitlets        : 5.7.1


In [ ]:
input=[np.array(data2023[i]['conditional_volatality']) for i in range(len(ticker_symbol))]
print(len(input))
corr_matrix = np.corrcoef(input)
print(corr_matrix)

eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
#print(eigenvalues)
#Find the principal eigenvector
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]
#print('largest index:',largest_index,'\nprincipal eigenvector:',principal_eigenvector)

def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices_v2023 = get_sorted_indices(eve.copy())

for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices_v2023[i]])


47
[[ 1.          0.80247488 -0.09096826 ... -0.0289579  -0.18041396
   0.2210662 ]
 [ 0.80247488  1.          0.02186262 ...  0.0449896  -0.06267727
   0.20507204]
 [-0.09096826  0.02186262  1.         ...  0.19374575  0.25153861
   0.06837398]
 ...
 [-0.0289579   0.0449896   0.19374575 ...  1.          0.08753424
   0.16853239]
 [-0.18041396 -0.06267727  0.25153861 ...  0.08753424  1.
   0.09034225]
 [ 0.2210662   0.20507204  0.06837398 ...  0.16853239  0.09034225
   1.        ]]
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
POWERGRID.NS
ITC.NS
HDFCBANK.NS
ICICIBANK.NS
INFY.NS
WIPRO.NS
BPCL.NS
BAJAJFINSV.NS
RELIANCE.NS
SUNPHARMA.NS
KOTAKBANK.NS
ULTRACEMCO.NS
TATAMOTORS.NS
NTPC.NS
EICHERMOT.NS
ASIANPAINT.NS
BRITANNIA.NS
HEROMOTOCO.NS
JSWSTEEL.NS
AXISBANK.NS
ONGC.NS
BHARTIARTL.NS
HCLTECH.NS
TITAN.NS
TECHM.NS
HINDUNILVR.NS
HINDALCO.NS
NESTLEIND.NS
DIVISLAB.NS
DRREDDY.NS
MARUTI.NS
CIPLA.NS
TA

In [ ]:
ticker_symbol=[47]
data=[]
ticker_symbol=['ADANIENT.NS','ADANIPORTS.NS','SHRIRAMFIN.NS','COALINDIA.NS','TATASTEEL.NS','BAJFINANCE.NS','BAJAJ-AUTO.NS','APOLLOHOSP.NS','LT.NS','INDUSINDBK.NS','M&M.NS','SBIN.NS','POWERGRID.NS','ITC.NS','HDFCBANK.NS','ICICIBANK.NS','INFY.NS','WIPRO.NS','BPCL.NS','BAJAJFINSV.NS','RELIANCE.NS','SUNPHARMA.NS','KOTAKBANK.NS','ULTRACEMCO.NS','TATAMOTORS.NS','NTPC.NS','EICHERMOT.NS','ASIANPAINT.NS','BRITANNIA.NS','HEROMOTOCO.NS','JSWSTEEL.NS','AXISBANK.NS','ONGC.NS','BHARTIARTL.NS','HCLTECH.NS','TITAN.NS','TECHM.NS','GRASIM.NS','HINDUNILVR.NS','TCS.NS','TATACONSUM.NS','CIPLA.NS','HINDALCO.NS','MARUTI.NS','DRREDDY.NS','NESTLEIND.NS','DIVISLAB.NS']
start_date='2011-08-01'
close_date='2014-07-31'

for i in range(47):
  data.append(yf.download(ticker_symbol[i],start=start_date,end=close_date))
  #print(len(data[i]))

for i in range(len(ticker_symbol)):
  for j in range(len(data[i])):
    data[i]=data[i].assign(returns=((np.log(data[i]['Close']))-(np.log(data[i]['Close'].shift(1)))))

for i in range(len(ticker_symbol)):
  data[i]['returns'][0]=0
  model=arch_model(data[i]['returns'],p=1,q=1)
  model_fit=model.fit(disp='off')
  data[i]=data[i].assign(conditional_volatality=(np.power(model_fit.conditional_volatility,3/2)))

input=[np.array(data[i]['returns']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)


eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices1114 = get_sorted_indices(eve.copy())
print('Based on returns the order by eigenvectors is')
for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices1114[i]])




input=[np.array(data[i]['conditional_volatality']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)

eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices_v1114 = get_sorted_indices(eve.copy())
print('Based on volatility the order by eigenvectors is')
for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices_v1114[i]])

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

Based on returns the order by eigenvectors is
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
ITC.NS
ICICIBANK.NS
INFY.NS
WIPRO.NS
BPCL.NS
RELIANCE.NS
NTPC.NS
EICHERMOT.NS
ASIANPAINT.NS
HEROMOTOCO.NS
JSWSTEEL.NS
HCLTECH.NS
TITAN.NS
TECHM.NS
TATACONSUM.NS
HINDALCO.NS
MARUTI.NS
DRREDDY.NS
NESTLEIND.NS
DIVISLAB.NS
CIPLA.NS
TCS.NS
HINDUNILVR.NS
GRASIM.NS
BHARTIARTL.NS
ONGC.NS
AXISBANK.NS
BRITANNIA.NS
TATAMOTORS.NS
ULTRACEMCO.NS
KOTAKBANK.NS
SUNPHARMA.NS
BAJAJFINSV.NS
HDFCBANK.NS
POWERGRID.NS
Based on volatility the order by eigenvectors is
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
POWERGRID.NS
ITC.NS
HDFCBANK.NS
ICICIBANK.NS
INFY.NS
WIPRO.NS
BPCL.NS
BAJAJFINSV.NS
RELIANCE.NS
SUNPHARMA.NS
KOTAKBANK.NS
ULTRACEMCO.NS
TATAMOTORS.NS
NTPC.NS
EICHERMOT.NS
ASIANPAINT.NS
BRITANNIA.NS
HEROMOTOCO.NS
JSWSTEEL

In [ ]:
ticker_symbol=[47]
data=[]
ticker_symbol=['ADANIENT.NS','ADANIPORTS.NS','SHRIRAMFIN.NS','COALINDIA.NS','TATASTEEL.NS','BAJFINANCE.NS','BAJAJ-AUTO.NS','APOLLOHOSP.NS','LT.NS','INDUSINDBK.NS','M&M.NS','SBIN.NS','POWERGRID.NS','ITC.NS','HDFCBANK.NS','ICICIBANK.NS','INFY.NS','WIPRO.NS','BPCL.NS','BAJAJFINSV.NS','RELIANCE.NS','SUNPHARMA.NS','KOTAKBANK.NS','ULTRACEMCO.NS','TATAMOTORS.NS','NTPC.NS','EICHERMOT.NS','ASIANPAINT.NS','BRITANNIA.NS','HEROMOTOCO.NS','JSWSTEEL.NS','AXISBANK.NS','ONGC.NS','BHARTIARTL.NS','HCLTECH.NS','TITAN.NS','TECHM.NS','GRASIM.NS','HINDUNILVR.NS','TCS.NS','TATACONSUM.NS','CIPLA.NS','HINDALCO.NS','MARUTI.NS','DRREDDY.NS','NESTLEIND.NS','DIVISLAB.NS']
start_date='2014-08-01'
close_date='2017-07-31'

for i in range(47):
  data.append(yf.download(ticker_symbol[i],start=start_date,end=close_date))
  #print(len(data[i]))

for i in range(len(ticker_symbol)):
  for j in range(len(data[i])):
    data[i]=data[i].assign(returns=((np.log(data[i]['Close']))-(np.log(data[i]['Close'].shift(1)))))

for i in range(len(ticker_symbol)):
  data[i]['returns'][0]=0
  model=arch_model(data[i]['returns'],p=1,q=1)
  model_fit=model.fit(disp='off')
  data[i]=data[i].assign(conditional_volatality=(np.power(model_fit.conditional_volatility,3/2)))

input=[np.array(data[i]['returns']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)


eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices1417 = get_sorted_indices(eve.copy())
print('based on return the order by eigenvector is')
for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices1417[i]])



input=[np.array(data[i]['conditional_volatality']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)

eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices_v1417 = get_sorted_indices(eve.copy())
print('Based on volatility the order by eigenvectors is')
for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices_v1417[i]])

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

based on return the order by eigenvector is
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
M&M.NS
SBIN.NS
ITC.NS
HDFCBANK.NS
ICICIBANK.NS
INFY.NS
BAJAJFINSV.NS
RELIANCE.NS
SUNPHARMA.NS
KOTAKBANK.NS
NTPC.NS
EICHERMOT.NS
HEROMOTOCO.NS
JSWSTEEL.NS
AXISBANK.NS
BHARTIARTL.NS
TECHM.NS
TCS.NS
TATACONSUM.NS
CIPLA.NS
HINDALCO.NS
MARUTI.NS
DRREDDY.NS
DIVISLAB.NS
NESTLEIND.NS
HINDUNILVR.NS
GRASIM.NS
TITAN.NS
HCLTECH.NS
ONGC.NS
BRITANNIA.NS
ASIANPAINT.NS
TATAMOTORS.NS
ULTRACEMCO.NS
BPCL.NS
WIPRO.NS
POWERGRID.NS
INDUSINDBK.NS
Based on volatility the order by eigenvectors is
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
POWERGRID.NS
ITC.NS
HDFCBANK.NS
ICICIBANK.NS
WIPRO.NS
BPCL.NS
KOTAKBANK.NS
ULTRACEMCO.NS
TATAMOTORS.NS
NTPC.NS
EICHERMOT.NS
ASIANPAINT.NS
JSWSTEEL.NS
AXISBANK.NS
CIPLA.NS
HINDALCO.NS
MARUTI.NS
NESTLEIND.NS
DIVISLAB.NS
DRRE

In [ ]:
ticker_symbol=[47]
data=[]
ticker_symbol=['ADANIENT.NS','ADANIPORTS.NS','SHRIRAMFIN.NS','COALINDIA.NS','TATASTEEL.NS','BAJFINANCE.NS','BAJAJ-AUTO.NS','APOLLOHOSP.NS','LT.NS','INDUSINDBK.NS','M&M.NS','SBIN.NS','POWERGRID.NS','ITC.NS','HDFCBANK.NS','ICICIBANK.NS','INFY.NS','WIPRO.NS','BPCL.NS','BAJAJFINSV.NS','RELIANCE.NS','SUNPHARMA.NS','KOTAKBANK.NS','ULTRACEMCO.NS','TATAMOTORS.NS','NTPC.NS','EICHERMOT.NS','ASIANPAINT.NS','BRITANNIA.NS','HEROMOTOCO.NS','JSWSTEEL.NS','AXISBANK.NS','ONGC.NS','BHARTIARTL.NS','HCLTECH.NS','TITAN.NS','TECHM.NS','GRASIM.NS','HINDUNILVR.NS','TCS.NS','TATACONSUM.NS','CIPLA.NS','HINDALCO.NS','MARUTI.NS','DRREDDY.NS','NESTLEIND.NS','DIVISLAB.NS']
start_date='2017-08-01'
close_date='2020-07-31'

for i in range(47):
  data.append(yf.download(ticker_symbol[i],start=start_date,end=close_date))
  #print(len(data[i]))

for i in range(len(ticker_symbol)):
  for j in range(len(data[i])):
    data[i]=data[i].assign(returns=((np.log(data[i]['Close']))-(np.log(data[i]['Close'].shift(1)))))

for i in range(len(ticker_symbol)):
  data[i]['returns'][0]=0
  model=arch_model(data[i]['returns'],p=1,q=1)
  model_fit=model.fit(disp='off')
  data[i]=data[i].assign(conditional_volatality=(np.power(model_fit.conditional_volatility,3/2)))

input=[np.array(data[i]['returns']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)


eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices1720 = get_sorted_indices(eve.copy())

for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices1720[i]])



input=[np.array(data[i]['conditional_volatality']) for i in range(len(ticker_symbol))]
corr_matrix = np.corrcoef(input)

eigenvalues, eigenvectors = np.linalg.eig(corr_matrix)
largest_index = np.argmax(eigenvalues)
principal_eigenvector = eigenvectors[:, largest_index]


def get_sorted_indices(eve):
  sorted_data = sorted(eve, reverse=True)
  indices = [np.where(eve == val)[0][0]for val in sorted_data]
  return sorted_data, indices

eve = eigenvalues
sorted_list, initial_indices_v1720 = get_sorted_indices(eve.copy())
print('Based on volatility the order by eigenvectors is')
for i in range(len(sorted_list)):
  print(ticker_symbol[initial_indices_v1720[i]])

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%*******

ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
POWERGRID.NS
ITC.NS
ICICIBANK.NS
INFY.NS
WIPRO.NS
BPCL.NS
TATAMOTORS.NS
NTPC.NS
EICHERMOT.NS
BRITANNIA.NS
HEROMOTOCO.NS
TCS.NS
TATACONSUM.NS
CIPLA.NS
MARUTI.NS
DIVISLAB.NS
NESTLEIND.NS
DRREDDY.NS
HINDALCO.NS
HINDUNILVR.NS
GRASIM.NS
TECHM.NS
TITAN.NS
HCLTECH.NS
BHARTIARTL.NS
ONGC.NS
AXISBANK.NS
JSWSTEEL.NS
ASIANPAINT.NS
ULTRACEMCO.NS
KOTAKBANK.NS
SUNPHARMA.NS
RELIANCE.NS
BAJAJFINSV.NS
HDFCBANK.NS
SBIN.NS
Based on volatility the order by eigenvectors is
ADANIENT.NS
ADANIPORTS.NS
SHRIRAMFIN.NS
COALINDIA.NS
TATASTEEL.NS
BAJFINANCE.NS
BAJAJ-AUTO.NS
APOLLOHOSP.NS
LT.NS
INDUSINDBK.NS
M&M.NS
SBIN.NS
ITC.NS
POWERGRID.NS
HDFCBANK.NS
ICICIBANK.NS
INFY.NS
WIPRO.NS
BPCL.NS
BAJAJFINSV.NS
RELIANCE.NS
SUNPHARMA.NS
KOTAKBANK.NS
ULTRACEMCO.NS
TATAMOTORS.NS
EICHERMOT.NS
NTPC.NS
ASIANPAINT.NS
BRITANNIA.NS
HEROMOTOCO.NS
JSWSTEEL.NS
AXISBANK.NS
ONGC.NS
BHARTIARTL.NS
HCLTECH.

In [ ]:
array=[initial_indices_v1720,initial_indices_v1417,initial_indices_v1114,initial_indices_v2023]
corr=np.corrcoef(array)
print(corr)

[[1.         0.76757632 0.99525902 0.99560592]
 [0.76757632 1.         0.79151249 0.76006013]
 [0.99525902 0.79151249 1.         0.99294635]
 [0.99560592 0.76006013 0.99294635 1.        ]]


In [ ]:
array=[initial_indices1720,initial_indices1417,initial_indices1114,initial_indices2023]
corr=np.corrcoef(array)
print(corr)

[[1.         0.95594357 0.97213228 0.95062442]
 [0.95594357 1.         0.99028677 0.98473636]
 [0.97213228 0.99028677 1.         0.98924607]
 [0.95062442 0.98473636 0.98924607 1.        ]]
